### ISSUE TITLE
[Improvement] Setting to disable automatic updates

### ISSUE THREAD

**Issue by gschier** [getinsomnia/insomnia#154]
## TODO

- [ ] Setting to disable update check
- [ ] Have a way to trigger update check manually (optional)
- [ ] Have a way to automatically check for updates, but not install automatically (optional)

**Comment by gschier** [comment]
Closing this one for now. Will revisit if demand increases.

**Comment by robotvert** [comment]
This would be useful for people like me oftentimes hacking on the road and tethering.
