### ISSUE TITLE
[Epic] Request Chaining

### ISSUE THREAD

**Issue by gschier** [getinsomnia/insomnia#210]
Request chaining is the ability to have a request depend on the response of another. For example, referencing an auth token from a _login_ request in a request to fetch a user's resources.

## Overview

The cleanest way to do this is via a custom Nunjucks tag.

```bash
# tag name, request ID, attribute, query
{% response 'req_123', 'body', '$.data.token' %}
```

## Features

- Reference values of the response of another request
- View dependencies of a request (ie. "Fetch User" depends on "Login")
- Automatically send dependent requests if they don't yet have responses (configurable?)
- Automatic query type detection
    - JSONPath, XPath, regex

## Deployable Steps

**Required:**<br>
- [x] Only render tags if they are used in a request #211 
    - Will prevent dependencies defined in the environment from executing if not referenced
- [x] Finish and finalize API for `{% response ... %}` tag #224 
- [x] Implement a tag editor specifically designed for the tag #234 
    - Helper to find the request and `<select>` the attribute, 

**Nice-to-have:**<br>
- [ ] Implement custom JSON-lint that ignores nunjucks tags/variables/comments
    - Right now `{ "foo": "{% uuid "v4" %}" }` causes a lint error. A complex tag like this one would make the problem even more common
- [ ] Separate requests by folder in request selection
- [ ] Add way to resend request dependencies
- [ ] Add way to show request's dependencies
- [ ] ... whatever else may be useful

**Comment by bayssmekanique** [comment]
Not that this isn't already a heady feature request, but has there been any consideration to allowing arbitrary code execution before a request?  It seems like there would be a significant amount of overlap with this feature request.

**Comment by shahalam786** [comment]
Lol

**Comment by gschier** [comment]
@bayssmekanique that will be part of the plugin framework #51

**Comment by mgraham** [comment]
Wow! Great feature!!

In the `Request` menu of the `Edit Tag` dialog It would be useful to organize the requests by folder.  I have a lot of requests that are named the same in different folders.

**Comment by mgraham** [comment]
Response tags do not seem to work in environments.  When the environment contains a `response` tag, the `Done` button remains disabled.

**Comment by gschier** [comment]
@mgraham thanks for the feedback! I added a to-do item to this issue for folder separation.

For environments, the JSON must be valid. Be sure you have double quotes around the tag.

![image](https://cloud.githubusercontent.com/assets/587576/26452779/0a0b9c04-4116-11e7-83ed-cba7f7dfb735.png)

**Comment by mgraham** [comment]
Duh - that was it!  Works now!  Thank you!

**Comment by gschier** [comment]
No problem @mgraham!

**Comment by gschier** [comment]
Going to close this one for now, as it is now possible to reference values from other requests. Any improvements will be submitted as separate issues.
