### ISSUE TITLE
[Feature] Duplicate Workspace

### ISSUE THREAD

**Issue by gschier** [getinsomnia/insomnia#233]
## What

Add functionality do duplicate a workspace

## To-do

Make these changes to the workspace settings modal.

- [x] Rename the "Danger Zone" section to "Actions"
- [x] Add button under "Actions" to duplicate workspace
- [x] Duplicate the workspace and all of its children
- [x] Activate the new workspace after duplication complete

## Notes

See app.js:219 for how a request is duplicated.

**Comment by gschier** [comment]
This was closed by #237
