### ISSUE TITLE
Add spectron for automated e2e testing

### ISSUE THREAD

**Issue by develohpanda** [getinsomnia/insomnia#2535]
- [x] Add spectron with a basic test #2531
- [x] Run with installed app #2531
- [x] Run with packaged app (after `npm run app-package`) #2531
- [x] Run with built app (after `npm run app-build`) #2531 #2537
- [x] Mock local server to query against #2544 
- [x] Add Core to PR pipeline #2536 
- [x] Run tests specific to Core vs Designer #2545 
- [x] Add Designer to PR pipeline #2549
- [x] Add to Linux PR pipeline #2536
- [ ] Add to Release pipeline - package and test
- [ ] Convert to ES6 style imports (investigate TS for the smoke-testing project)
- [ ] Update `userData` to set the app data directory - https://github.com/electron-userland/spectron/blob/master/test/commands-test.js#L214-L217
