### ISSUE TITLE
[Git Sync] Diff before commit and the commit action itself are slow

### ISSUE THREAD

**Issue by AyresMonteiro** [getinsomnia/insomnia#6454]
### Expected Behavior

It would be possible to quickly do git diff of added/removed/modified request, as shown below.
![image](https://github.com/Kong/insomnia/assets/53703706/fe52c719-af3b-49b2-b901-47b1c6dfa89d)

And it would be possible to quickly commit using the commit button:
![image](https://github.com/Kong/insomnia/assets/53703706/65891dee-211e-4997-853e-80e2c6d7b89b)

### Actual Behavior

The diff takes a long time (about 10+ minutes) to finish:
![image](https://github.com/Kong/insomnia/assets/53703706/61a9192d-0f97-477e-a1e8-33c524fd2a4d)

And commit button is also slow. It spin out for a long time before accomplish any commit.

### Reproduction Steps

Just install Insomnia in debian-based linux and try to sync the repository using git.

Using a VM could be util.

Edit: other users reported the same error on Windows, so you can test it too. At the present date, the error was not reported in macOS.

### Is there an existing issue for this?

- [X] I have searched the [issue tracker](https://www.github.com/Kong/insomnia/issues) for this problem.

### Additional Information

There is another bug already reported in issue tracker by other people that I've found: git sync not working properly after project cloning.

To solve it I just reset my git sync setup and it started to work. Not properly (as mentioned above in this issue), but it started to work.

### Insomnia Version

2023.5.6

### What operating system are you using?

Ubuntu

### Operating System Version

Mint 21 Vanessa

### Installation method

Using dpkg alongside downloadable .deb in Insomnia site.

```[tasklist]
### Tasks
- [ ] Debug git sync slowness
- [ ] Fix git sync slowness
```

**Comment by m1h43l** [comment]
Diff and commit is extremely slow. Windows 10. Insomnia 2023.5.5

**Comment by AyresMonteiro** [comment]
> Diff and commit is extremely slow. Windows 10. Insomnia 2023.5.5

Thanks for the reply! I removed the "[Linux]" tag from title due to knowing that the problem exists in other OS

**Comment by mirket999** [comment]
It is crazy slow and doesn`t response most of the time, for me as well.

**Comment by dbt-lucka** [comment]
Can confirm, Windows 10

**Comment by dimi-lcq** [comment]
Look at this ticket, same problem ...
https://github.com/Kong/insomnia/issues/3269

**Comment by AyresMonteiro** [comment]
> Look at this ticket, same problem ... #3269

By the way, I saw that your ticket was from April 8th, 2021 and I was wondering in which version the bug was introduced or if it was always slow since the first version of Insomnia's git integration.

In addition, I never used git sync previously... I was using a version of Insomnia from 2020 before and there was not this git apparat, so I can't tell when the problem started.

**Comment by bryangateley** [comment]
Has anyone figured out where the source folders are for the repo when using git w/ insomnia? Wouldn't it be easier to just do all changes through the CLI? I tried looking for where the git repo is saved locally but was unable to.

**Comment by AyresMonteiro** [comment]
> Has anyone figured out where the source folders are for the repo when using git w/ insomnia? Wouldn't it be easier to just do all changes through the CLI? I tried looking for where the git repo is saved locally but was unable to.

I know that there are some `.db` files that are probably used by Insomnia to handle its data.

Looking in the `.config/Insomnia/` directory I've found this file `insomnia.GitRepository.db` but I didn't look it properly yet. When I'm not busy I'll try to figure out how this file is handled by Insomnia.

**Comment by gatzjames** [comment]
Closing as this has been significantly improved in latest versions of the app
